local_backend: true

media_folder: "public/images"
public_folder: "/images"

backend:
  name: proxy
  branch: main
  proxy_url: http://localhost:8081/api/v1

collections:
  - name: "Main"
    label: "Main"
    folder: "src/_content/main"
    create: true
    extension: "mdx"
    slug: "{{fields.slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "clinics-switzerland"
    label: "Clinics in Switzerland"
    folder: "src/_content/clinics/switzerland"
    create: true
    extension: "mdx"
    slug: "{{fields.slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Country", name: "country", widget: "string" }
      - { label: "City", name: "city", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "clinics-turkey"
    label: "Clinics in Turkey"
    folder: "src/_content/clinics/turkey"
    create: true
    extension: "mdx"
    slug: "{{fields.slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Country", name: "country", widget: "string" }
      - { label: "City", name: "city", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "springs"
    label: "Springs"
    folder: "src/_content/springs"
    create: true
    extension: "mdx"
    slug: "{{fields.slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "spas"
    label: "Spas"
    folder: "src/_content/spas"
    create: true
    extension: "mdx"
    slug: "{{fields.slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "Services"
    label: "Services"
    folder: "src/_content/services"
    create: true
    extension: "mdx"
    slug: "{{fields.slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
