local_backend: true

media_folder: "public/images"
public_folder: "/images"

backend:
  name: proxy
  branch: main
  proxy_url: http://localhost:8081/api/v1

collections:
  - name: "Main" # /admin/collections/main
    label: "Main" # Used in the UI
    folder: "src/_content/main" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "mdx"
    slug: "main/{{fields.slug}}"
    format: "frontmatter"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "clinics-switzerland" # /admin/collections/main
    label: "Clinics in Switzerland" # Used in the UI
    folder: "src/_content/clinics/switzerland" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "mdx"
    slug: "{{fields.slug}}"
    format: "frontmatter"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Country", name: "country", widget: "string" }
      - { label: "City", name: "city", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "clinics-turkey" # /admin/collections/main
    label: "Clinics in Turkey" # Used in the UI
    folder: "src/_content/clinics/turkey" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "mdx"
    slug: "{{fields.slug}}"
    format: "frontmatter"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Country", name: "country", widget: "string" }
      - { label: "City", name: "city", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "springs" # /admin/collections/main
    label: "Springs" # Used in the UI
    folder: "src/_content/springs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "mdx"
    slug: "{{fields.slug}}"
    format: "frontmatter"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "spas" # /admin/collections/main
    label: "Spas" # Used in the UI
    folder: "src/_content/spas" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "mdx"
    slug: "{{fields.slug}}"
    format: "frontmatter"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
